# Generated by Django 6.0.2 on 2026-02-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("current_price", models.FloatField()),
                ("pe_ratio", models.FloatField(blank=True, null=True)),
                ("discount_level", models.FloatField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
