# Generated by Django 6.0.2 on 2026-03-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
        ("portfolio", "0002_stock_analytics_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to="staff.staff",
            ),
        ),
    ]
