# Generated by Django 6.0.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="current_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="stock_id",
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name="stock",
            name="max_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="min_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="opportunity_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="stock",
            name="discount_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "stock_id"),
                name="unique_stock_per_portfolio",
            ),
        ),
    ]
