# Generated by Codex on 2026-03-09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_portfolio_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stock",
            name="eps",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="intrinsic_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="market_cap",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
